permalink: /:categories/:year/:month/:day/:title 

exclude: ["README.md"]
pygments: true
debug: true

title: "Canal Web"
tagline: "Cellular automata analysis tool"
description: "Canal is a web based cellular automata analysis tool. You can set your initial state and run any of the ECA rules on it. There are more options that extends the possibilities of analysis and simulations."
keywords: "cellular automata elementary html5 eca"
image: "/img/meta-image.gif"

author :
  name : "Edwin Rodríguez"
  email : "edwrodrig@gmail.com"
  page: "http://edwrodrig.github.io"
  services:
    twitter: edwrodrig

production_url: "http://edwrodrig.github.io/canal-web"
google_tracking_id: "UA-49580762-3"

type:
  name: "github_project"
  github_project:
    user: "edwrodrig"
    name: "canal-web"
    branch: "gh-pages"

sharing:
  style: "square"
  services:
    - "facebook"
    - "twitter"
    - "google-plus"
    - "pinterest"
    - "github"

markdown: kramdown